//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_
    {
        public int user_id { get; set; }
        public string username { get; set; }
        public string password_user { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Phonenumber { get; set; }
        public string City { get; set; }
    }
}
